### ISSUE TITLE
installation with cupy from pip

### ISSUE THREAD

**Issue by marclava** [briangu/klongpy#3]
`pip3 install klongpy[gpu,repl]` tries to install cupy from source, 
but cupy is already available for different CUDA backends, using specific pip packages: https://pypi.org/project/cupy/

Is there an easy way to install klongpy with support for cupy using the cupy wheels?

Edit: I downloaded the source,  changed the requirements, and installed the package with `pip install -e .[gpu,repl]`

**Comment by briangu** [comment]
Good question.  I'll take a look.  Thanks!

**Comment by marclava** [comment]
This is working for me (in setup.py):
<pre>
    extras_require={
        'cuda12x': ["cupy-cuda12x"],
        'cuda11x': ["cupy-cuda11x"],
        'cuda111': ["cupy-cuda111"],
        'cuda110': ["cupy-cuda110"],
        'cuda102': ["cupy-cuda102"],
        'rocm-5-0': ["cupy-rocm-5-0"],
        'rocm-4-3': ["cupy-rocm-4-3"],
        'repl': ["colorama"],
    }
</pre>

**Comment by briangu** [comment]
Cool! I’ll take a look later todayOn Mar 5, 2023, at 12:24 PM, Marc Lavallée ***@***.***> wrote:﻿
This is working for me (in setup.py):
    extras_require={
        'cuda12x': ["cupy-cuda12x"],
        'cuda11x': ["cupy-cuda11x"],
        'cuda111': ["cupy-cuda111"],
        'cuda110': ["cupy-cuda110"],
        'cuda102': ["cupy-cuda102"],
        'rocm-5-0': ["cupy-rocm-5-0"],
        'rocm-4-3': ["cupy-rocm-4-3"],
        'repl': ["colorama"],
    }

**Comment by briangu** [comment]
I've merged your suggestion along with README changes.  Thanks!

**Comment by briangu** [comment]
I've merged your suggestion along with README changes. Thanks!
