### ISSUE TITLE
IPC

### ISSUE THREAD

**Issue by jibanes** [briangu/klongpy#4]
Brian,

What is the best way to pass a klong "object" to another process, either local or remote?

**Comment by briangu** [comment]
That's an interesting question.  Currently there's no way to serialize the KlongInterpeter, however, it is basically a dictionary, so one quick way would be to send a "state" dictionary to the remote Klong server and populate the state via puts.  When time allows, I've been working on https://github.com/briangu/kdfs which is meant to be more like a KlongPy as a server, allowing Klong via RPC (TCP) to make things like ticker plants.

So a couple ideas come to mind: either i figure out a way to serialize KlongContext tree, or just enumerate the KlongInterpreter context (I think i'd need to add dictionary enumeration to walk the context), or send commands to the remote KlongInterpeter to build the context "over there".  The tricky thing of sending state could be that marshaling big numpy arrays could be annoying vs using something like the DFS project to load a pandas dataframe "over there".

Does this help?

**Comment by jibanes** [comment]
Yeah I see the logic, I didn't know about kdfs, thanks for pointing me to that. Serialization vs enumeration, I think both would be useful, see, I think we should be able to save the "state" as well?

**Comment by briangu** [comment]
If i understand correctly, you are suggesting something like:

```
klong('kdb_objects') = kdbobjects
image = klong.to_image()
# write to file or send over network
newKlong = KlongInterpeter.from_image(image)
kdbobjects = newKlong('kdb_objects')
# continue "over here"
```

does this seem accurate?

**Comment by jibanes** [comment]
it would be interesting to consider something like this, but maybe there
isn't much value adding interoperability with kdb+ in the end. Companies
running kdb+ are quite unlikely to migrate to klong at this time.

**Comment by briangu** [comment]
yeah that makes sense, i was more in thinking of it as a binary blob.  so i think the aggregate suggestion from above makes more sense to me.

in any case, the idea of to_image and from_image seems compelling.

**Comment by jibanes** [comment]
+1

**Comment by briangu** [comment]
In case you are interested, i'm working over in the kdfs repo to add use cases for IPC, ticker plant, etc.  I recently added a simple example of a websocket based ticker plant that uses KlongPy to handle stock messages.  I'm thinking about what the operators would be for IPC that would marshal across processes.  These aren't features of the Klong itself, so need to be thoughtful.

**Comment by jibanes** [comment]
excellent, thank you! How do you represent a timestamp (i.e. 2023.03.10T15:32:52.974) in klongpy?

**Comment by briangu** [comment]
that's a very good question! At first glance, I'd bias towards leveraging python integration and add some python time functions as Klong functions:

1. use klong to build strings and pass them to python functions like strptime

e.g.
```
klong['strptime'] = lambda x: datetime.strptime(x, "%d %B, %Y")
```
and do something like:

```
a::strptime("2023.03.10T15:32:52.974")
```
which would yield a datetime object in klong interpeter context.

you could then do things like:

```
d:::{};d,"timestamp",a
```
which actually looks like:
```
{'timestamp': datetime.datetime(2018, 6, 21, 0, 0)}
```
in memory. I did this in the REPL.

```
>>> from datetime import datetime
>>> from klongpy import KlongInterpreter
>>> klong = KlongInterpreter()
>>> klong['strptime'] = lambda x: datetime.strptime(x, "%d %B, %Y")
>>> klong('a::strptime("21 June, 2018")')
datetime.datetime(2018, 6, 21, 0, 0)
>>> klong['a']
datetime.datetime(2018, 6, 21, 0, 0)
>>> klong('d:::{};d,"timestamp",a')
{'timestamp': datetime.datetime(2018, 6, 21, 0, 0)}
```
It's pretty interesting, this Klong + Python integration!

You could easily go one step further to make a proper timestamp integer:

```
>>> klong['strptime'] = lambda x: datetime.strptime(x, "%d %B, %Y").timestamp()
>>> klong('strptime("21 June, 2018")')
1529560800.0
```

Keep in mind, that the python lambdas have to follow the same x,y,z input param guidelines as Klong functions themselves.

**Comment by jibanes** [comment]
This is extremely useful indeed!

**Comment by briangu** [comment]
Following up on this, I've updated the Klong interpreter with functionality to make Python interop much simpler:

Call a Python function from Klong:

```python
from klongpy import KlongInterpreter
klong = KlongInterpreter()
klong['f'] = lambda x, y, z: x*1000 + y - z
r = klong('f(3; 10; 20)')
assert r == 2990
```

and vice versa, you can call a Klong function from Python:

```python
from klongpy import KlongInterpreter
klong = KlongInterpreter()
klong("f::{(x*1000) + y - z}")
r = klong['f'](3, 10, 20)
assert r == 2990
```

**Comment by jibanes** [comment]
This is great, I was planning of "connecting" kdfs to interactive brokers and paper trade using a few strategies from kdb+ to klong (simple stuff first, like vwap etc) and this makes it much easier.

**Comment by briangu** [comment]
Awesome.  Yes, that exactly the goal. I'm starting to take a look at user-defined kernels for CuPy backend.  It's interesting because when you access the reduction paths in GPU (e.g. +/!100) it's just so blazingly fast.

**Comment by briangu** [comment]
that's why i made the DFS project, which is basically a pandas dataframe service.  it's a relatively simple solution but it allows a process (e.g. the realtime service) to push to a historical at the end of the day.  I added a dfs client example in the kdfs repo which pushes realtime changes to the DFS server.  I think the next step is to have an inmemory solution for realtime and then as you suggest, EOD push to the DFS for safe keeping.

https://github.com/briangu/dfs
https://github.com/briangu/kdfs/blob/main/kdfs/handlers/dfs_client.py

**Comment by jibanes** [comment]
Perfect indeed, I think this way should allow easy interoperability with statistical analysis tools, have you considered charting too?

**Comment by briangu** [comment]
I have a start on some websocket based charting but needs more work. 

There's also arctic by the man group which basically gave me the idea for the DFS. I found their reliance on mongo overlay complicated.

**Comment by jibanes** [comment]
websocket would be nice, so it can be automatically updated. I didn't know about arctic, glad your code is easier to read  and less complex lol
