### ISSUE TITLE
Bug in join over

### ISSUE THREAD

**Issue by jairtrejo** [briangu/klongpy#5]
Hello, Brian! Thank you so much for KlongPy. I'm writing a [ray tracer in Klong](https://github.com/jairtrejo/klong-rt) (following [Ray Tracing in One Weekend](https://raytracing.github.io/books/RayTracingInOneWeekend.html)) and it has made it fast enough to be practical.

I discovered an issue with join over. The program:

```
,/[[[1 2] [3 4]] [[5 6] [7 8]]]
```

In klongpy returns:

```
[[1 2 5 6]
 [3 4 7 8]]
```

Whereas in klong it correctly returns:

```
[[1 2] [3 4] [5 6] [7 8]]
```

It seems to be doing the joining "inside-out". My workaround is using "over neutral" with an empty list:

```
?>[],/[[[1 2] [3 4]] [[5 6] [7 8]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

**Comment by briangu** [comment]
Hello Jair,

Thanks so much for the bug report! I'll take a look.

Neat raytracer project!

Cheers,
Brian

**Comment by briangu** [comment]
Hello,
I've gotten some time to dig into this.  Thanks for pointing out this issue! It uncovered some latent issues that I'm working through.  I should have a new version of KlongPy quite soon.
Cheers!
Brian

**Comment by briangu** [comment]
New version released with fix and new tests.
