### ISSUE TITLE
Format2 doesn't work on arrays

### ISSUE THREAD

**Issue by teichert** [briangu/klongpy#7]
In attempting to follow the [klong intro](https://t3x.org/klong/klong-intro.txt.html), I noticed that Format2 doesn't seem to work on arrays in cpu klongpy.  (I'm using klongpy-0.5.8.)

Expression: `[1]$[1]`
Expected Result (observed in [klong](https://t3x.org/klong/klong20221212.tgz)): `["1"]`
Observed Result: `Error: ('only integer scalar arrays can be converted to a scalar index',)`

Note, `1$1` does give the right result of `"1"`.
The README mentions some restrictions on using string with the cupy version of klongpy, but that seemed to only apply to the cupy version.

**Comment by briangu** [comment]
Hello! Thanks! I'll take a look at the format2 issue.

I'm not entirely sure what your CuPy question is but due to the limits of CuPy itself, not all Klong operations will work on GPU.    On CPU / NumPy everything should work as expected.

**Comment by briangu** [comment]
looking at the klong reference here https://t3x.org/klong/klong-ref.txt.html , given a$b, a should be an integer.   

> "The minimal size of the output string is specified in "a", which must be an integer."

so you can definitely do 1$[1] which yields: "[1]"

I'm going to think about what [1]$[1] means in the context of Klong.

The error message is definitely opaque, which is issue worthy.

**Comment by teichert** [comment]
First of all, thanks for your great work on this very interesting project and for taking a look at this issue!

> I'm going to think about what [1]$[1] means in the context of Klong.

From the [klong reference](https://t3x.org/klong/klong-ref.txt.html) describing the semantics of arguments to atomic dyadic operators: "When both operands are lists, their elements are combined pairwise.", so I would expect that `[1]$[1]` should result in a list with a single element which is the result of applying the `$` operator to `1` and `1`.  Similarly `[4 3]$[2 1]` should give `["2 
  " "1  "]`, just like `[4 3]+[2 1]` gives `[6 4]`.

In case it might serve as a helpful clue, a possibly related issue (probably should be opened as a separate issue---maybe just a matter of documenting it) is that an additional difference between the behavior of klongpy and of klong proper is that klongpy allows numpy-style broadcasting of argument arrays whereas klong proper simply allows lists of the same length to operate pairwise or scalars to operate on all members of a corresponding list.  Because of this, `[4 3] + 2` yields `[6 5]` in both klongpy and klong proper, while `[4 3] + [2]` yields the same result (`[6 5]`) in klongpy, but gives an error `kg: error: plus: shape error: [[4 3] [2]]` in klong proper.  (I actually think the numpy broadcasting is a useful feature of klongpy, but it is a difference in semantics from klong proper and I wonder if it might be related to the issue with Format2 acting differently in klongpy.)  Perhaps the behavior of atomic operators like + and * gets the elementwise behavior correct because they correspond to built-in numpy operators and broadcasting does the right thing, but if the `$` operator isn't a native numpy ufunc, then maybe it doesn't attempt broadcasting in the same way and therefore behaves differently.)

(Sorry for not taking the time to look into the code/PR at this point!)

**Comment by briangu** [comment]
That's a very interesting observation on broadcasting.  I have been accumulating a list of deltas from native Klong as it's clear KlongPy will be a superset.   I need to talk to Neils to get his view on some of this stuff, but areas like slicing of a numpy array is trivial in KlongPy but Klong doesn't support it.  Also, all the IPC and extensions are pretty different than native Klong as I've not yet found a satisfying way to map some things back to Klong Channels.

Broadcasting should definitely be called out and documented clearly and I much appreciate your details as I hadn't noticed this.  I should create a new .kg test suite for just the extensions.

BTW, I'm planning on writing an online book for KlongPy to cover all the complex use cases, such as ticker plants, etc.

**Comment by briangu** [comment]
Also, I'm glad you find KlongPy useful!

**Comment by briangu** [comment]
issue has been fixed on main and will be pushed out in next release: 0.6.0

**Comment by briangu** [comment]
version 0.6.0 released
